---
title: "Incidence (pre)diabetes vs number of viruses and viral co-occurrence"
author: "Tim Woelfle"
date: "17/01/2022"
output:
  html_notebook:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r init}
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(ggtext))
suppressPackageStartupMessages(library(UpSetR))
suppressPackageStartupMessages(library(ComplexHeatmap))

data = readRDS("imputed.rds")

viruses = c("hsv1", "hsv2", "vzv", "ebv", "cmv", "hhv6", "hhv7")

viruses_f4 = paste0("uh_",viruses,"class")

data = data[
    data$f4dm == "Normal" &
    data$ff4dm != "missing" &
    !(is.na(data$uh_vzvclass) & is.na(data$u3h_vzvclass)) & !is.na(data$uh_hsv1), ]

data[is.na(data$uh_vzvclass), "uh_vzvclass"] = data[is.na(data$uh_vzvclass), "u3h_vzvclass"]

data$num_vir_f4 = rowSums(data[viruses_f4])

cov_mod1 = c("male", "utalter")
cov_mod2 = c(cov_mod1, "utbmi", "ltedyrs", "ever_smoker", "utphys")
cov_mod3 = c(cov_mod2, "utmvdiab", "utwhom", "ul_trin", "utchohdl", "uthoma_ir")
cov_mod4 = c(cov_mod3, "utglukfast_n")
```

# Number of viruses

```{r, fig.width=8, fig.height=5, message=FALSE}
pie_data = data[data$f4dm == "Normal" & !rowSums(is.na(data[,viruses_f4])),]
pie_data$ff4dm = droplevels(pie_data$ff4dm)
pie_data$ff4dm = factor(pie_data$ff4dm, levels=c("T2D", "Prediabetes", "Normal"), labels=c("Incident (pre)diabetes", "Incident (pre)diabetes", "Normal glucose tolerance"))

palette = c("firebrick3", "dodgerblue3")
p1=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 1,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")
p2=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 2,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")
p3=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 3,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")
p4=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 4,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")
p5=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 5,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")
p6=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 6,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")
p7=ggpie(as.data.frame(table(Status=pie_data[pie_data$num_vir_f4 == 7,"ff4dm"])), "Freq", lab.pos="in", fill="Status", palette = palette) + theme(legend.position = "none")

mod_crude = glm(pie_data$ff4dm!="Normal glucose tolerance" ~ ., pie_data["num_vir_f4"], family="binomial")
mod_adj = glm(pie_data$ff4dm!="Normal glucose tolerance" ~ ., pie_data[c("num_vir_f4", cov_mod4)], family="binomial")

#summary(mod_crude)
#summary(mod_adj)

#https://rpkgs.datanovia.com/ggpubr/reference/stat_compare_means.html
pvalAsterisks = function(pval) {
  return(symnum(pval, cutpoints = c(0, 0.001, 0.01, 0.05, 1), symbols = c("***", "**", "*", "")))
}

text_crude = paste0("OR = ", round(exp(coef(summary(mod_crude))[2,2]),2), " (", round(exp(confint(mod_crude)[2,1]),2), ", ", round(exp(confint(mod_crude)[2,2]),2), ") <i>p</i>=", signif(coef(summary(mod_crude))[2,4],1), " ", pvalAsterisks(coef(summary(mod_crude))[2,4]))

text_adj = paste0("OR = ", round(exp(coef(summary(mod_adj))[2,2]),2), " (", round(exp(confint(mod_adj)[2,1]),2), ", ", round(exp(confint(mod_adj)[2,2]),2), ") <i>p</i>=", signif(coef(summary(mod_adj))[2,4],1), " ", pvalAsterisks(coef(summary(mod_adj))[2,4]))

pl1 = ggpar(
  # if common.legend = T is put here, it's below the chi-square subtitle
  #ggarrange(NULL,p1,p2,p3,p4,p5,p6,p7,p8,p9,NULL, ncol=11, widths=c(0.8,rep(1,9),0.3)),
  ggarrange(NULL,p1,p2,p3,p4,p5,p6,p7,NULL, ncol=9, widths=c(0.8,rep(1,7),0.3)), 
  #title=paste0("Number of seropositive viruses vs. diabetic status in F4 (n=", nrow(pie_data), ")"), font.title=c(16,"bold","black"),
  #subtitle=paste0("chi-square p=", signif(summary(table(pie_data$num_vir_f4, pie_data$ff4dm))$p.value,2)), font.subtitle=c(12,"plain","black")
  subtitle=paste0("Number of viruses:<br>Unadjusted ", text_crude, "<br>Adjusted ", text_adj), font.subtitle=c(12,"plain","black")
) + theme(
  plot.subtitle = element_markdown()
)

pl2 = ggplot(pie_data, aes(x=num_vir_f4, fill=ff4dm, color=ff4dm)) + geom_bar() + scale_fill_manual(values=palette) + scale_color_manual(values=palette) + theme_pubr() + theme(legend.position = "none") + xlab("Number of seropositive viruses") + ylab("Number of probands") + scale_x_continuous(breaks=1:7) + theme(legend.title=element_blank())

ggarrange(pl1,pl2,nrow=2, heights=c(0.35,0.65), common.legend = T)

# pdf("Figure 4A.pdf", width=8, height=5)
# ggarrange(pl1,pl2,nrow=2, heights=c(0.35,0.65), common.legend = T)
# dev.off()
```


# Co-occurrence map

```{r, warning=FALSE}
for (var in viruses_f4) {
  data[,var] = as.integer(data[,var])
}

# Incidence
plot_data = data[complete.cases(data[viruses_f4]) & data$f4dm == "Normal", c("ff4dm",viruses_f4)]
colnames(plot_data) = c("ff4dm", toupper(viruses))
plot_data$ff4dm = plot_data$ff4dm != "Normal"
plot_data$ff4dm_int = as.integer(plot_data$ff4dm) + 1

# Chi-square test for first 15 columns
m=make_comb_mat(plot_data[toupper(viruses)])
set_sizes = sort(comb_size(m), decreasing=T)
mat = matrix(c(
  table(plot_data[extract_comb(m, names(set_sizes[1])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[2])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[3])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[4])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[5])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[6])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[7])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[8])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[9])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[10])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[11])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[12])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[13])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[14])), "ff4dm"]),
  table(plot_data[extract_comb(m, names(set_sizes[15])), "ff4dm"])
  ),
  ncol=2, byrow=T
)
#mat = mat[1:15,1:3]
summary(as.table(mat))
#rowSums(mat)

upset_plot = upset(plot_data, sets=toupper(viruses), nintersects=15, order.by="freq", line.size=NA, query.legend="top",
      queries = list(
        #list(query.name="Incident T2D", query=elements, params = list("ff4dm_int", 1,2,3), color="firebrick3", active=T),
        list(query.name="Incident (pre)diabetes", query=elements, params = list("ff4dm_int", 1,2), color="firebrick3", active=T),
        list(query.name="Normal glucose tolerance", query=elements, params = list("ff4dm_int", 1), color="dodgerblue3",active=T)
      )
)

upset_plot

# pdf("Figure 4B.pdf", width=8, height=5)
# upset_plot
# dev.off()
```

## Standardised resdiuals

```{r}
#https://stats.stackexchange.com/questions/111986/post-hoc-chi2-test-with-r
chisq.posthoc.test <-
  function(x,
           method = "bonferroni",
           round = 6,
           ...) {
    # Perform the chi square test and save the residuals
    stdres <- chisq.test(x)$stdres
    # Calculate the chi square values based on the residuls
    chi_square_values <- stdres ^ 2
    # Get the p values for the chi square values
    p_values <- pchisq(chi_square_values, 1, lower.tail = FALSE)
    # Adjust the p values with the chosen method
    adjusted_p_values <- p_values
    for (i in 1:nrow(adjusted_p_values)) {
      adjusted_p_values[i, ] <- p.adjust(
        adjusted_p_values[i, ],
        method = method,
        n = ncol(adjusted_p_values) * nrow(adjusted_p_values)
      )
    }
    # Round the adjusted p values
    adjusted_p_values <- round(adjusted_p_values, digits = round)
    # Convert stdres and adjusted p values into data frames
    stdres <- as.data.frame.matrix(stdres)
    adjusted_p_values <- as.data.frame.matrix(adjusted_p_values)
    # Combine residuals and p values into one table
    results <-
      as.data.frame(matrix(
        data = NA,
        nrow = nrow(adjusted_p_values) * 2,
        ncol = ncol(adjusted_p_values) + 2
      ))
    odd_rows <- seq(1, nrow(results), 2)
    even_rows <- seq(2, nrow(results), 2)
    results[odd_rows, c(3:ncol(results))] <- stdres
    results[even_rows, c(3:ncol(results))] <- adjusted_p_values
    results[odd_rows, 2] <- "Residuals"
    results[even_rows, 2] <- "p values"
    colnames <- dimnames(x)[[2]]
    colnames <- append(colnames, c("Dimension", "Value"), after = 0)
    colnames(results) <- colnames
    rownames <- dimnames(x)[[1]]
    results[odd_rows, 1] <- rownames
    results[even_rows, 1] <- rownames
    # Return the results
    results
  }

rownames(mat) = 1:15
chisq.posthoc.test(mat, method="none")
```

# Session info

For reproducibility

```{r}
sessionInfo()
```
