---
title: "Supplementary"
author: "Tim Woelfle"
date: "17/01/2022"
output:
  html_notebook:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r init}
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggalluvial))

data = readRDS("imputed.rds")

viruses = c("hsv1", "hsv2", "vzv", "ebv", "cmv", "hhv6", "hhv7")

viruses_f4 = paste0("uh_",viruses,"class")
viruses_ff4 = paste0("u3h_",viruses,"class")

data$num_vir_f4 = rowSums(data[viruses_f4])
data$num_vir_ff4 = rowSums(data[viruses_ff4])

round = function(x, digits=0) sprintf(paste0("%.", digits, "f"), x)
 
signif_p = function(x, digits=1) {
  if (x < 0.001) return("<0.001")
  x = signif(x, digits)
  return(paste0("=", as.character(x)))
}
signif_p = Vectorize(signif_p, "x")
```

# Demographic tables

## Differences participants / non-participants

```{r, results='asis', warning=FALSE}
data_f4 = read.csv("Erg3_K05119n_woelfle_tra_V2007.csv", row.names = "zz_nr")
erg = read.csv2("pv_51_19n_erg5.csv", row.names = "zz_nr")
data_f4 = data_f4[!is.na(data_f4$utalter),]
data_f4[,colnames(erg)] = erg[rownames(data_f4),]

data_f4$ul_trin = as.numeric(data_f4$ul_trin)
data_f4$utchohdl = as.numeric(data_f4$utchohdl)
data_f4$utglukfast_n = as.numeric(data_f4$utglukfast_n)
data_f4$utmvdiab[data_f4$utmvdiab==3] = NA

data_f4$uh_hsv1class = data_f4$uh_hsv1 > 100
data_f4$uh_hsv2class = data_f4$uh_hsv2 > 100
data_f4$uh_hhv7class = data_f4$uh_hhv7u14 > 100

participants = data_f4[rownames(data),]
non_participants = data_f4[!rownames(data_f4) %in% rownames(data),]

n_percent = function(x) {
  len = length(x)
  na = sum(is.na(x))
  x = x[!is.na(x)]
  text = paste0(sum(x), " (", round(mean(x)*100,1), "%)")
  if (na) text = paste0(text, ", ", na, " (", round(na/len*100,1), "%) NA")
  text
}
comp_n_percent = function(x,y) {
  p = prop.test(c(sum(x,na.rm=T), sum(y,na.rm=T)), c(sum(!is.na(x)), sum(!is.na(y))))$p.value
  return(c(n_percent(x), n_percent(y), signif_p(p)))
}

median_iqr = function(x) {
  len = length(x)
  na = sum(is.na(x))
  x = x[!is.na(x)]
  text = paste0(median(x), " (IQR ", quantile(x, 0.25), "-", quantile(x, 0.75), ", range ", min(x), "-", max(x), ")")
  if (na) text = paste0(text, ", ", na, " (", round(na/len*100,1), "%) NA")
  text
}
comp_median_iqr = function(x,y) {
  p = wilcox.test(x,y)$p.value
  return(c(median_iqr(x), median_iqr(y), signif_p(p)))
}

create_table1 = function(x,y,x_label,y_label,diab=T) {
  df = as.data.frame(t(data.frame(
    male = comp_n_percent(x$ucsex==1, y$ucsex==1),
    age = comp_median_iqr(x$utalter, y$utalter),
    bmi = comp_median_iqr(x$utbmi, y$utbmi),
    edu = comp_median_iqr(x$ltedyrs, y$ltedyrs),
    smok = comp_n_percent(x$utcigreg_sf!=4, y$utcigreg_sf!=4),
    phys = comp_n_percent(x$utphys==1, y$utphys==1),
    parental_diab = comp_n_percent(x$utmvdiab==1, y$utmvdiab==1),
    hypertension = comp_n_percent(x$utwhom>1, y$utwhom>1),
    trigly = comp_median_iqr(x$ul_trin, y$ul_trin),
    cholhdl = comp_median_iqr(x$utchohdl, y$utchohdl),
    homa_ir = comp_median_iqr(x$uthoma_ir, y$uthoma_ir),
    fast_glu = comp_median_iqr(x$utglukfast_n, y$utglukfast_n),
    
    hsv1 = comp_n_percent(x$uh_hsv1class, y$uh_hsv1class),
    hsv2 = comp_n_percent(x$uh_hsv2class, y$uh_hsv2class),
    vzv = comp_n_percent(x$uh_vzvclass, y$uh_vzvclass),
    ebv = comp_n_percent(x$uh_ebvclass, y$uh_ebvclass),
    cmv = comp_n_percent(x$uh_cmvclass, y$uh_cmvclass),
    hhv6 = comp_n_percent(x$uh_hhv6class, y$uh_hhv6class),
    hhv7 = comp_n_percent(x$uh_hhv7class, y$uh_hhv7class),
    row.names=c(paste0(x_label, " (n=", nrow(x), ")"), paste0(y_label, " (n=", nrow(y), ")"), "Difference p-value")
  )))
  
  if (diab) df = rbind(df,
    ifgigt = comp_n_percent(x$utdm100y15 %in% c(1,2,3), y$utdm100y15 %in% c(1,2,3)),
    t2d = comp_n_percent(x$utdm100y15 %in% c(4,5), y$utdm100y15 %in% c(4,5)),
    other_diab = comp_n_percent(x$utdm100y15 %in% c(6,7), y$utdm100y15 %in% c(6,7)),
    missing_ogtt = comp_n_percent(x$utdm100y15 == 8, y$utdm100y15 == 8)
  )
  
  df
}

knitr::kable(create_table1(participants, non_participants, "Participants", "Non-Participants"))
```

### At risk only

```{r}
participants = data_f4[rownames(data),]
participants = participants[participants$utdm100y15 == 0,]
non_participants = data_f4[!rownames(data_f4) %in% rownames(data),]
non_participants = non_participants[non_participants$utdm100y15 == 0,]

knitr::kable(create_table1(participants, non_participants, "At Risk Participants", "At Risk Non-Participants", diab=F))
```

# Viral prevalence

```{r}
plot_data = data[!is.na(data["uh_hsv1"]) & !is.na(data["u3h_hsv1"]),
                 c(paste0("uh_", viruses, "class"), paste0("u3h_", viruses, "class"))]
#plot_data = data[f4ff4, c(paste0("uh_", viruses, "class"), paste0("u3h_", viruses, "class"))]
#colnames(plot_data) = toupper(viruses)
plot_data = plot_data %>% gather("virus", "F4")
plot_data[1:(nrow(plot_data)/2), "FF4"] = plot_data[(nrow(plot_data)/2+1):nrow(plot_data), "F4"]
plot_data = plot_data[1:(nrow(plot_data)/2),]

plot_data$virus = factor(plot_data$virus, c(paste0("uh_", viruses, "class"), paste0("u3h_", viruses, "class")), rep(toupper(viruses),2))

# remove VZV missings (overlap is only 1540 for VZV)
plot_data = plot_data[complete.cases(plot_data),]

tab_f4 = table(virus=plot_data$virus, status=plot_data$F4)
tab_ff4 = table(virus=plot_data$virus, status=plot_data$FF4)

plot_data = rbind(
  as.data.frame(tab_f4),
  as.data.frame(tab_ff4))
plot_data$timepoint = rep(c("F4","FF4"), each=nrow(plot_data)/2)
plot_data$status = factor(plot_data$status, c(FALSE, TRUE), c("seronegative","seropositive"))

#plot_data$virus = rep(c("HSV1 ns", "HSV2 *", "VZV ***", "EBV ns", "CMV ns", "HHV6 ****", "HHV7 ****"), times=4)

# position="fill" scales bars to the same height and changes y-axis to frequency from count
ggplot(plot_data, aes(x=timepoint, y=Freq, fill=status)) + geom_col(position="fill") + facet_grid(.~virus) + scale_fill_manual(values=c("dodgerblue3","firebrick3")) + theme_pubr() + xlab(NULL) + ylab("Prevalence")

#Compare prevalence-difference
#http://www.promesa.co.nz/help/EP_est_compare_prev.htm
for (virus in viruses) {
  virus = toupper(virus)
  p1 = prop.table(tab_f4, 1)[virus,2] # prevalence F4
  p2 = prop.table(tab_ff4, 1)[virus,2] # prevalence FF4
  n1 = sum(tab_f4[virus,])
  n2 = sum(tab_ff4[virus,])
  
  
  p = (tab_f4[virus,2]+tab_ff4[virus,2])/(n1+n2)
  z = (p2-p1)/sqrt(p*(1-p)*(1/n1+1/n2))
  
  print(paste0(virus, " prevalence F4: ", signif(p1,2), ", FF4: ", signif(p2,2)))
  print(paste0(virus, " prevalence diff FF4-F4: ", 
               signif(p2-p1,2), " (95% CI ",
               signif(p2-p1-1.96*sqrt(p1*(1-p1)/n1 + (p2*(1-p2)/n2)),2), " - ",
               signif(p2-p1+1.96*sqrt(p1*(1-p1)/n1 + (p2*(1-p2)/n2)), 2), ") z=", signif(z,2), ", p=", signif(pnorm(-z)*2,2)))
}
```

# Number of viruses: Sankey

```{r sankey, fig.width=9, fig.height=6}
plot_data = data[data$f4dm != "missing" & data$ff4dm != "missing" & !rowSums(is.na(data[,viruses_f4])) & !rowSums(is.na(data[,viruses_ff4])),]

print(paste0("Num of viruses for 1540 overlapping subjects at F4: ", mean(plot_data$num_vir_f4), " +- ", sd(plot_data$num_vir_f4)))
print(paste0("Num of viruses for 1540 overlapping subjects at FF4: ", mean(plot_data$num_vir_ff4), " +- ", sd(plot_data$num_vir_ff4)))
t.test(plot_data$num_vir_f4, plot_data$num_vir_ff4)

#signif(prop.table(table(plot_data$num_vir_f4==plot_data$num_vir_ff4)),2)
#signif(prop.table(table(plot_data$num_vir_f4< plot_data$num_vir_ff4)),2)
#signif(prop.table(table(plot_data$num_vir_f4> plot_data$num_vir_ff4)),2)

plot_data[,"num_vir_f4"] = factor(plot_data[,"num_vir_f4"], 7:1, c(7:3,"1 & 2","1 & 2"))
plot_data[,"num_vir_ff4"] = factor(plot_data[,"num_vir_ff4"], 7:1, c(7:3,"1 & 2","1 & 2"))
links = table(Source=plot_data[,"num_vir_f4"], Target=plot_data[,"num_vir_ff4"], useNA="always") %>% as.data.frame()
links = links[links$Freq != 0,]

print(ggplot(links, aes(y=Freq, axis1=Source, axis2=Target)) +
  geom_alluvium() +
  #scale_fill_manual(values=) +
  geom_stratum(fill = "lightgrey", color = "black") +
  geom_label(stat = "stratum", label.strata=T) +#, nudge_y=45
  #geom_text(aes(label=Freq), stat = "stratum", nudge_y=-45) +
  scale_x_discrete(limits = c("F4", "FF4")) +
  ylab("") +# scale_fill_manual(values=palette) +
  theme( panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.y = element_blank(), axis.text.x = element_text(size = 12, face = "bold"), axis.ticks.y = element_blank(), panel.background = element_rect(fill = "white") ))
```


# Diabetes incidence F4-FF4 (Sankey)

```{r, fig.width=9, fig.height=6}
f4ff4 = data[
  data$f4dm != "missing" &
  data$ff4dm != "missing" &
  !is.na(data$uh_hsv1), ]

f4ff4$f4dm = factor(f4ff4$f4dm, levels=c("T2D", "Prediabetes", "Normal"))
f4ff4$ff4dm = factor(f4ff4$ff4dm, levels=c("T2D", "Prediabetes", "Normal"))

links = table(Source=f4ff4$f4dm, Target=f4ff4$ff4dm, useNA="always") %>% as.data.frame()
links = links[links$Freq != 0,]

palette = c("firebrick3", "gold1", "dodgerblue3")

ggplot(links, aes(y=Freq, axis1=Source, axis2=Target)) +
  geom_alluvium(aes(fill=Target)) +
  geom_stratum(fill = "lightgrey", color = "black") +
  geom_label(stat = "stratum", label.strata=T, nudge_y=50) +
  geom_text(aes(label=Freq), stat = "stratum", nudge_y=-50) +
  scale_x_discrete(limits = c("F4", "FF4")) +
  ylab("") +
  theme( panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.y = element_blank(), axis.text.x = element_text(size = 12, face = "bold"), axis.ticks.y = element_blank(), panel.background = element_rect(fill = "white") ) + scale_fill_manual(values=palette) +
  theme(legend.position="none")

links
```

# Diabetes covariates

```{r, fig.width=11, fig.height=7, warning=FALSE}
palette = c("dodgerblue3", "gold1", "firebrick3")

demo = data[data$f4dm != "missing" & !is.na(data$uh_hsv1), c("f4dm", "utalter", "male", "utbmi", "utpyrs_ai", "ltedyrs")]
demo$f4dm = droplevels(demo$f4dm)
colnames(demo) = c("Status", "Age", "Male", "BMI", "Packyears", "Years")

age_plot = ggviolin(demo, x="Status", y="Age", fill="Status", add="boxplot", add.params = list(fill = "white")) +
  stat_compare_means(comparisons = list(c("Normal", "Prediabetes"), c("Normal", "T2D")), label = "p.signif", label.y=c(98,105)) +
  guides(fill=F) + xlab("") + ggtitle("Age") +
  scale_fill_manual(values=palette) + ylim(NA,110)

bmi_plot = ggviolin(demo, x="Status", y="BMI", fill="Status", add="boxplot", add.params = list(fill = "white")) +
  stat_compare_means(comparisons = list(c("Normal", "Prediabetes"), c("Normal", "T2D")), label = "p.signif") +
  guides(fill=F) + xlab("") + ggtitle("BMI") +
   scale_fill_manual(values=palette) + ylim(NA,60)

smoking_plot = ggviolin(demo, x="Status", y="Packyears", fill="Status", add="boxplot", add.params = list(fill = "white")) +
  stat_compare_means(comparisons = list(c("Normal", "Prediabetes"), c("Normal", "T2D")), label = "p.signif", label.y=c(167,187)) +
  guides(fill=F) + xlab("") + ggtitle("Smoking") +
   scale_fill_manual(values=palette) + ylim(c(NA,200))

education_plot = ggviolin(demo, x="Status", y="Years", fill="Status", add="boxplot", add.params = list(fill = "white")) +
  stat_compare_means(comparisons = list(c("Normal", "Prediabetes"), c("Normal", "T2D")), label = "p.signif", label.y=c(19,20.5)) +
  guides(fill=F) + xlab("") + ggtitle("Education") +
   scale_fill_manual(values=palette) + ylim(NA, 22)

ggarrange(age_plot, bmi_plot, smoking_plot, education_plot, nrow=2, ncol=2) + theme(legend.position="none")
```

# Session info

For reproducibility

```{r}
sessionInfo()
```
